### PR TITLE
Upgrade Gradle to 8.5

### PR DESCRIPTION
**Pull request by supl**
## Description

This PR upgrades the build system to Gradle 8.5. This is mainly for building this project (running the gradle wrapper) with Java 21.

## Related issues and/or PRs

N/A

## Changes made

- upgraded the Gradle wrapper

## Checklist

- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation to reflect the changes.
- [ ] Any remaining open issues linked to this PR are documented and up-to-date (Jira, GitHub, etc.).
- [x] Tests (unit, integration, etc.) have been added for the changes.
- [x] My changes generate no new warnings.
- [ ] Any dependent changes in other PRs have been merged and published.

### CODE REVIEW

**Review by kota2and3kan — COMMENTED** [review]
Thank you for the update!
I have one question.
From now, do we support only Java 21 or later in Scalar Admin for Kubernetes?
In other words, from the perspective of Scalar Manager, is it OK to support only Java 21 or later?
(From the perspective of users, basically, they use pre-built binary or container image. So, I think there is no problem. However, I want to confirm it from the perspective of library users (mainly us).)

**Comment by supl** [comment]
> Thank you for the update! I have one question. From now, do we support only Java 21 or later in Scalar Admin for Kubernetes? In other words, from the perspective of Scalar Manager, is it OK to support only Java 21 or later? (From the perspective of users, basically, they use pre-built binary or container image. So, I think there is no problem. However, I want to confirm it from the perspective of library users (mainly us).)

@kota2and3kan 

Sorry, I might have confused you.

This change is for running the gradle wrapper, for example, `./gradlew build` with Java 21 but not about scalar-admin-for-kubernetes.

For scalar-admin-for-kubernetes library, users can still integrate it with Java 8. (The class files in the JAR are still using major version 52 which Java 8 can run)

My OS-level Java version is upgraded to 21 and I noticed my VSCode couldn't run Gradle so I upgraded the Gradle wrapper version to 8.5 based on this https://docs.gradle.org/current/userguide/compatibility.html

**Comment by kota2and3kan** [comment]
@supl 
I see. I understood.
Thank you for your explanation!

**Review by kota2and3kan — APPROVED** [review]
LGTM! Thank you!

**Review by feeblefakie — APPROVED** [review]
LGTM! Thank you!

**Pull request merged**
